name: build

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: windows-2019
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    steps:
      - uses: actions/checkout@v2

      - name: Build
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" hello/hello.vcxproj /p:Platform=Win32 /p:Configuration=Release'
      
      - name: Build (x64)
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" hello/hello.vcxproj /p:Platform=x64 /p:Configuration=Release'
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello
          path: |
           bin/Release/hello.exe
           bin/Release/hello-x64.exe
